imports:
  - path: vm_instance.py
  - path: vm_multiple_instances.py
  - path: common.py
  - path: default.py
  - path: regional_multi_vm.py

resources:
- name: test
  type: regional_multi_vm.py
  properties:
    sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1410-utopic-v20150625
    zones: 
    - us-central1-a
    #- europe-west1-b
    #- asia-east1-a
    machineType: n1-standard-1
    network: default
    numberOfVMReplicas: 1
    disks:
    - deviceName: vm-test-data-disk
      type: PERSISTENT
      boot: false
      autoDelete: true
      initializeParams:
        diskType: pd-ssd
        diskSizeGb: 10
    bootDiskType: pd-standard

    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          mkdir -p /mnt/data
          chmod 777 /mnt/data
          /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/disk/by-id/google-${HOSTNAME}-test-data-disk /mnt/data
          apt-get update
          apt-get install openjdk-7-jdk -yqq
