imports:
  - path: common/common.py
    name: common.py
  - path: common/default.py
    name: default.py
  - path: common/vm_instance.py
    name: vm_instance.py
  - path: common/vm_multiple_instances.py
    name: vm_multiple_instances.py
  - path: datastax.py
  - path: regional_multi_vm.py
  - path: datastax_wrapper.py

resources:
- name: datastax
  type: datastax_wrapper.py
  properties:
    machineType: n1-standard-1
    diskSize: 10
    dataDiskType: pd-standard
    instanceBaseName: service
    nodeType: cassandra
    nodesPerZone: 1
    opsCenterZone: us-central1-f
    zoneUsEast1b: false
    zoneUsEast1c: false
    zoneUsEast1d: false
    zoneUsCentral1a: false
    zoneUsCentral1b: false
    zoneUsCentral1c: false
    zoneUsCentral1f: true
    zoneEuropeWest1b: false
    zoneEuropeWest1c: false
    zoneEuropeWest1d: false
    zoneAsiaEast1a: false
    zoneAsiaEast1b: false
    zoneAsiaEast1c: false
    network: default
